version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
    volumes:
      - mongo_data:/data/db

  # ---------------- NATS 集群 ----------------
  nats1:
    image: nats:latest
    container_name: nats1
    restart: always
    ports:
      - "4222:4222"   # 客户端连接端口
      - "6222:6222"   # 集群内部通信端口
      - "8222:8222"   # 监控端口
    command: >
      -js
      -server_name nats1
      -cluster_name nats-cluster
      -cluster nats://0.0.0.0:6222
      -routes nats://nats2:6222,nats://nats3:6222
      -http_port 8222

    networks:
      - nats_net

  nats2:
    image: nats:latest
    container_name: nats2
    restart: always
    ports:
      - "4223:4222"
      - "6223:6222"
      - "8223:8222"
    command: >
      -js
      -server_name nats2
      -cluster_name nats-cluster
      -cluster nats://0.0.0.0:6222
      -routes nats://nats1:6222,nats://nats3:6222
      -http_port 8223
 
    networks:
      - nats_net

  nats3:
    image: nats:latest
    container_name: nats3
    restart: always
    ports:
      - "4224:4222"
      - "6224:6222"
      - "8224:8222"
    command: >
      -js
      -server_name nats3
      -cluster_name nats-cluster
      -cluster nats://0.0.0.0:6222
      -routes nats://nats1:6222,nats://nats2:6222
      -http_port 8224
  
    networks:
      - nats_net
 
  # ---------------- ETCD 集群 ----------------
  etcd1:
    image: bitnami/etcd:latest
    container_name: etcd1
    restart: always
    ports:
      - "2379:2379"
      - "2380:2380"
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_NAME=etcd1
      - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://etcd1:2380
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd1:2379
      - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_INITIAL_CLUSTER=etcd1=http://etcd1:2380,etcd2=http://etcd2:2380,etcd3=http://etcd3:2380
      - ETCD_INITIAL_CLUSTER_STATE=new
    networks:
      - my_network

  etcd2:
    image: bitnami/etcd:latest
    container_name: etcd2
    restart: always
    ports:
      - "2381:2379"
      - "2382:2380"
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_NAME=etcd2
      - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://etcd2:2380
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd2:2379
      - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_INITIAL_CLUSTER=etcd1=http://etcd1:2380,etcd2=http://etcd2:2380,etcd3=http://etcd3:2380
      - ETCD_INITIAL_CLUSTER_STATE=new
    depends_on:
      - etcd1
    networks:
      - my_network

  etcd3:
    image: bitnami/etcd:latest
    container_name: etcd3
    restart: always
    ports:
      - "2383:2379"
      - "2384:2380"
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_NAME=etcd3
      - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://etcd3:2380
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd3:2379
      - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_INITIAL_CLUSTER=etcd1=http://etcd1:2380,etcd2=http://etcd2:2380,etcd3=http://etcd3:2380
      - ETCD_INITIAL_CLUSTER_STATE=new
    depends_on:
      - etcd1
      - etcd2
    networks:
      - my_network

# ---------------- 持久化存储 ----------------
  # redis:
  #   image: redis:latest
  #   container_name: redis
  #   restart: always
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - redis_data:/data
  #   command: ["redis-server", "--appendonly", "yes"]
  #   networks:
  #     - redis_net
volumes:
  mongo_data:
  # redis_data:

# ---------------- 网络 ----------------
networks:
  my_network:
    driver: bridge
  mongo_net:
    driver: bridge
  nats_net:
    driver: bridge
  # redis_net:
  #   driver: bridge
  #   internal: true
